from sqlalchemy import Column, Integer, Text, text

from scryfall_clone.db.engine import Base


class Token(Base):
    __tablename__ = "tokens"

    id = Column(Integer, primary_key=True)
    artist = Column(Text)
    asciiName = Column(Text)
    availability = Column(Text)
    boosterTypes = Column(Text)
    borderColor = Column(Text)
    colorIdentity = Column(Text)
    colors = Column(Text)
    faceName = Column(Text)
    finishes = Column(Text)
    flavorText = Column(Text)
    frameEffects = Column(Text)
    frameVersion = Column(Text)
    hasFoil = Column(Integer, nullable=False, server_default=text("0"))
    hasNonFoil = Column(Integer, nullable=False, server_default=text("0"))
    isFullArt = Column(Integer, nullable=False, server_default=text("0"))
    isFunny = Column(Integer, nullable=False, server_default=text("0"))
    isPromo = Column(Integer, nullable=False, server_default=text("0"))
    isReprint = Column(Integer, nullable=False, server_default=text("0"))
    isTextless = Column(Integer, nullable=False, server_default=text("0"))
    keywords = Column(Text)
    language = Column(Text)
    layout = Column(Text)
    mcmId = Column(Text)
    mtgArenaId = Column(Text)
    mtgjsonV4Id = Column(Text)
    multiverseId = Column(Text)
    name = Column(Text)
    number = Column(Text)
    originalText = Column(Text)
    originalType = Column(Text)
    otherFaceIds = Column(Text)
    power = Column(Text)
    promoTypes = Column(Text)
    reverseRelated = Column(Text)
    scryfallId = Column(Text)
    scryfallIllustrationId = Column(Text)
    scryfallOracleId = Column(Text)
    securityStamp = Column(Text)
    setCode = Column(Text)
    side = Column(Text)
    signature = Column(Text)
    subtypes = Column(Text)
    supertypes = Column(Text)
    tcgplayerProductId = Column(Text)
    text = Column(Text)
    toughness = Column(Text)
    type = Column(Text)
    types = Column(Text)
    uuid = Column(Text(36), nullable=False)
    watermark = Column(Text)
